### ISSUE TITLE
README

### ISSUE THREAD

**Issue by unicodeveloper** [andela-iadeniyi/Potato-ORM#1]
1. `Potato-ORM is a package that manages the CRUD operation od database` .  od should have been of.
2.  Usage

```php
<?php
    use Ibonly\PotatoORM\User;

    echo $sugar->getAll();
?>
```

There is no demonstration of where `$sugar` is coming from for this and all other examples

**Comment by unicodeveloper** [comment]
@andela-iadeniyi you haven't taken care of this

**Comment by andela-iadeniyi** [comment]
I have updated it.

**Comment by unicodeveloper** [comment]
Alright . Please Check the *Credits Section* . I still see `Open-source Evangelist` there which shouldn't be the case.

**Comment by andela-iadeniyi** [comment]
Corrected.
